### ISSUE TITLE
erro autocomplete jquery-1.11.1.js?compile=false:9176

### ISSUE THREAD

**Issue by biosystem** [vahidhedayati/ajaxdependancyselection#10] opened 2015-05-25 19:03 UTC
Good afternoon I'm trying to use the autocomplete and shows me the following error:
GET http://localhost:8089/bioweb/autoComplete/autocomplete?domain=bioweb.centro_custo&searchField=descricao&max=10&order=asc&collectField=id&term=i 403 (Forbidden) jQuery.ajaxTransport.send @ jquery-1.11.1.js compile = false: 9631jQuery.extend.ajax @ jquery-1.11.1.js compile = false: 9176e.widget._initSource.e.isArray. string.options.source.source @ jquery-ui.min.js compile = false: 7e.widget._search @ jquery-ui.min.js compile = false: 7 (anonymous function) @ jquery-ui.min. ? js compile = false: 6e.widget.search @ jquery-ui.min.js compile = false:? 7 (anonymous function) @ jquery-ui.min.js compile = false: 6 (anonymous function) @ jquery- ? ui.min.js compile = false: 7i @ jquery-ui.min.js compile = false: 6

Follows the way of how I'm using:
```gsp
<Label> CentroCustos: </ label>
        <G: autocomplete
            id = "primarySearch"
            controller = ""
            action = ""
            name = "centrocustos_id"
            domain = 'bioweb.centro_custo'
            searchField = 'description'
            collectField = 'id'
            value = "$ {params.myId}"
            max = "10"
            order = "asc"
            required = "false"
        />

```

**Comment by vahidhedayati** [comment] 2015-05-25 20:18
Hi Biosystem, 

You would need to add this to your call in order to load the local jquery-ui:
```
loadjui='enable'
```
https://github.com/vahidhedayati/ajaxdependancyselection/blob/4a9c40de2e4050a2a23c2cb3812737e7b1ae9e2f/grails-app/taglib/grails/plugin/ajaxdependancyselection/AutoCompleteTagLib.groovy#L722


Other than that you would need to provide your own jquery and jquery-ui

Can you please confirm the configuration / version of both as well as what grails version you are using 

I will then setup the same setup and try to find a fix. I suspect the version of jquery-ui  possibly in the plugin is the issue.

**Comment by biosystem** [comment] 2015-05-25 21:23
Hello I'm using grail 2.5

**Comment by vahidhedayati** [comment] 2015-05-25 21:43
thanks and you are using jquery-ui as well ? If so what version. Also have you tried adding 

```
loadjui='enable' 
```
to your g:autocomeplete call to see if it changes anything ? you should only need to call it once per any amount of call on any page.  

Or simply add 
```
<g:loadjui /> 
```
above the g:autoComplete call you are making to see if it makes any difference

**Comment by biosystem** [comment] 2015-05-25 21:53
<label>CentroCustos:</label>
        <g:loadjui/>
        <g:autocomplete
            id="primarySearch"
            controller = "contasPagar"
            action = ""
            name="centrocustos_id"
            domain='bioweb.centro_custo'
            searchField='descricao'
            collectField='id'
            value="${params.myId}"
            max="10"
            order="asc"
            required="false"
        />
![erro1](https://cloud.githubusercontent.com/assets/6421227/7802585/4350ec22-030f-11e5-8e86-86690fe87071.png)

**Comment by biosystem** [comment] 2015-05-25 21:55
My javascripts.
![javascripts](https://cloud.githubusercontent.com/assets/6421227/7802600/9f0517a0-030f-11e5-84cf-7b18c2966e0b.png)

**Comment by vahidhedayati** [comment] 2015-05-25 22:31
Please refer to my previous comment, I have just downloaded grails 2.5.0 and setup a demo site that appears to be working with auto complete:

https://github.com/vahidhedayati/testads5/blob/master/grails-app/views/layouts/main.gsp#L20
```
<g:loadjui /> 	
```

This has been added to my main layout which loads in jquery-ui into my app and is loaded on each page that loads in the main layout.

You could set this up on the gsp page that is making the actual g:autocomplete call.

In order for autoComplete to work it relies on jquery-ui, grails by default does not provide you with this and you could set up jquery-ui in grails by adding the plugin and configuration required. Or simple load it in as you see

I tested this from that demo site:
https://github.com/vahidhedayati/testads5/blob/master/grails-app/views/myContinent/example.gsp#L242

and it appeared to work fine, I loaded up the site and clicked on variety ..
```
git clone https://github.com/vahidhedayati/testads5.git
cd testads5
grails run-app
```

**Comment by biosystem** [comment] 2015-05-25 22:46
vahidhedayati

Hand me I skype to talk . or hangout

**Comment by vahidhedayati** [comment] 2015-05-26 12:35
you can reach me on hangouts : https://github.com/vahidhedayati/ajaxdependancyselection/blob/grails2/AjaxdependancyselectionGrailsPlugin.groovy#L10  

But I won't be able to help you until after 5:30 pm GMT (today) since I am at work

**Comment by vahidhedayati** [comment] 2015-05-27 22:06
Ok sorry been busy and I should have updated your answers to get a better idea of what you were actually defining in the call:
```gsp
<label>CentroCustos:</label>
        <g:loadjui/>
        <g:autocomplete
            id="primarySearch"
            name="centrocustos_id"
            domain='bioweb.centro_custo'
            searchField='descricao'
            collectField='id'
            value="${params.myId}"
            max="10"
            order="asc"
            required="false"
        />
```
Try above, you had defined:

```gsp
   controller = "contasPagar"
   action = ""
```

This maybe the cause of your issue, since by declaring this, typically you are telling the plugin that you prefer to take over the process of producing the JSON result that is fed back to the taglib call... 

If you now look at your screen shot, the last 404 the actual URL:

```
http://localhost:8089/bioweb/contasPagar/autoComplete?.... 404
```

So you have told the plugin to access, no Action default being: 

[attrs.action= "autocomplete"](https://github.com/vahidhedayati/ajaxdependancyselection/blob/master/grails-app/taglib/grails/plugin/ajaxdependancyselection/AutoCompleteTagLib.groovy#L432)

To access it on the defined controller name:
http://localhost:8089/bioweb/contasPagar/autoComplete this won't exist on your project and hence will make the actual call fail.

Please remove controller and action to fix this issue.

**Comment by biosystem** [comment] 2015-05-27 22:43
Okay,

The error may be in jquery for several js use in my project.

He is automatically placing the URL.

Enter hongouts?


GET http://localhost:8089/bioweb/autoComplete/autocomplete?domain=bioweb.centro_custo&searchField=descricao&max=10&order=asc&collectField=id&term=INF 403 (Forbidden)jQuery.ajaxTransport.send @ jquery-1.11.1.js?compile=false:9631jQuery.extend.ajax @ jquery-1.11.1.js?compile=false:9176e.widget._initSource.e.isArray.string.options.source.source @ jquery-ui.min.js?compile=false:7e.widget._search @ jquery-ui.min.js?compile=false:7(anonymous function) @ jquery-ui.min.js?compile=false:6e.widget.search @ jquery-ui.min.js?compile=false:7(anonymous function) @ jquery-ui.min.js?compile=false:6(anonymous function) @ jquery-ui.min.js?compile=false:7i @ jquery-ui.min.js?compile=false:6

**Comment by vahidhedayati** [comment] 2015-05-28 06:16
Hi sorry for not responding earlier I think we're in different time zones.


The new problem is 403 forbidden

Sounds like you  got some forms of security enabled that  is stopping the ultimate from being accessible 

Take a look at https://stackoverflow.com/questions/20026279/i-want-my-selects-dropdowns-to-auto-populate-with-ajax-in-grails-website

If you  read the comments. This user also had same issue until security changes in their  app. 

Regards

**Comment by biosystem** [comment] 2015-05-28 14:20
Error |
2015-05-28 11:20:24,813 [http-bio-8089-exec-8] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /bioweb/autoComplete/autocomplete - parameters:
collectField: id
max: 10
order: asc
term: INF
domain: bioweb.centro_custo
searchField: descricao
Cannot get property 'clazz' on null object. Stacktrace follows:
Message: Cannot get property 'clazz' on null object
    Line | Method
->>   44 | autocompletePrimaryAction in grails.plugin.ajaxdependancyselection.AutoCompleteService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     23 | autocomplete              in grails.plugin.ajaxdependancyselection.AutoCompleteController
|    198 | doFilter . . . . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter                  in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter . . . . . . . .  in grails.plugin.multitenant.core.servlet.CurrentTenantServletFilter
|     49 | doFilter                  in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
|     82 | doFilter . . . . . . . .  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1145 | runWorker                 in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    724 | run                       in java.lang.Thread

**Comment by vahidhedayati** [comment] 2015-05-28 16:04
https://github.com/vahidhedayati/ajaxdependancyselection/blob/master/grails-app/services/grails/plugin/ajaxdependancyselection/AutoCompleteService.groovy#L44

```groovy
   def domainClass = grailsApplication.getDomainClass(domain).clazz
```


```groovy
domain: bioweb.centro_custo
searchField: descricao
```

This is definitely your domainClass and its package convention ?

I mean I have never created any domain classes with underscores..

Can you please post that domainClass contents 

using this key 3 times all together before pasting and after the code block :  ` ` ` 

```groovy
package  bioweb

class centroCusto{

String descricao
}
```

If your package name is exactly as it is and if the class is centroCusto as I have done then your domain should be:


```groovy
domain: bioweb.centroCusto
searchField: descricao
```


This is not a database query so you would not to change appName to app_name, it requires actual object to query

**Comment by biosystem** [comment] 2015-05-28 16:26
Thank you friend,

It worked perfectly changed the class domain to CentroCusto . Now this one accusing the image of the error and already put it in the directory follows the error.

GET http : // localhost: 8089 / Bioweb / assets / images / ui- bg_highlight - soft_100_eeeeee_1x100.png 404 ( Not Found)

**Comment by vahidhedayati** [comment] 2015-05-28 17:32
ui- bg_highlight - soft_100_eeeeee_1x100.png  is part of jquery-ui, since you are loading up the jquery-ui from the plugin, I have taken a look and I am missing images. 

Let me fix it test it and give you an update.

**Comment by vahidhedayati** [comment] 2015-05-28 18:33
try the updated version 0.45

**Comment by biosystem** [comment] 2015-05-28 18:36
In the table contasPagar not this saving in centrocustos_id field below shows how I'm doing

Save the table contasPagar the field centrocustos_id

<label>CentroCustos:</label>
        <g:loadjui/>
        <g:autocomplete
                id="primarySearch"
                name="centrocustos_id"
                domain='bioweb.CentroCusto'
                searchField='descricao'
                collectField='id'
                value="${contasPagarInstance?.centrocustos?.descricao}"
                max="10"
                order="asc"
                required="true"
        />

**Comment by biosystem** [comment] 2015-05-28 18:50
Sorry as I update the version ?

**Comment by biosystem** [comment] 2015-05-28 18:56
version update. tank you

**Comment by biosystem** [comment] 2015-05-28 18:57
In the table contasPagar not this saving in centrocustos_id field below shows how I'm doing

Save the table contasPagar the field centrocustos_id

CentroCustos:

id="primarySearch"
name="centrocustos_id"
domain='bioweb.CentroCusto'
searchField='descricao'
collectField='id'
value="${contasPagarInstance?.centrocustos?.descricao}"
max="10"
order="asc"
required="true"
/>

**Comment by vahidhedayati** [comment] 2015-05-28 19:04
I suggest you send your form result to a test page/controller that does either in controller:

```groovy
println "${params}"
```

or in gsp

```gsp
${params}
```

and view what is being sent to see what it is you are looking for and what you need it to be 


I have no idea about your setup and unsure what 
```
centrocustos_id
```
is meant to be if  this is some relationship it should possible be 

```
centrocustos.id
```

You can find this sort of information out by generating the CRUD i.e. generate-controller generate-view for the given domainClass

Then view the gsp fields defined and it may give you a better clue

**Comment by biosystem** [comment] 2015-05-28 19:19
the scaffold he generated as follows:

_form.gps
<label for="centrocustos">
            <g:message code="contasPagar.centrocustos.label" default="Centrocustos"/>
            <span class="required-indicator">*</span>
        </label>

        <g:select id="centrocustos" name="centrocustos.id" from="${bioweb.CentroCusto.list()}" optionKey="id" required=""
                  value="${contasPagarInstance?.centrocustos?.id}" class="many-to-one"/>

index.gsp:
<g:if test="${contasPagarInstance?.centrocustos}">
                            <li class="fieldcontain">
                                <span id="centrocustos-label" class="property-label"><g:message
                                        code="contasPagar.centrocustos.label" default="Centrocustos"/></span>

                                <span class="property-value" aria-labelledby="centrocustos-label"><g:link
                                        controller="centroCusto" action="show"
                                        id="${contasPagarInstance?.centrocustos?.id}">${contasPagarInstance?.centrocustos?.encodeAsHTML()}</g:link></span>

                            </li>
                        </g:if>

**Comment by vahidhedayati** [comment] 2015-05-28 19:28
its right there: centrocustos.id so you need to change the centrocustos_id to centrocustos.id and hopefully it will work.

I take it you are quite new to grails, although this is kind of unrelated:
https://github.com/vahidhedayati/testads5/blob/master/grails-app/conf/BootStrap.groovy

It gives you an idea of objects in your controller (if all that centrocustos?.id fails)

You could get the object Custos and save it as the object like you see in bootstrap

so 
```
def myCustro = Custro.get(params.centrocustos_id)  //if you leave it as it is.
def c1 = centroCusto.findOrSaveWhere(custos: myCustro, otherField: otherValue...)
```

where custos is what ever you have defined the relationship
```
static hasMany = [ Custos: custos]
```

and myCustro is the object that is picked up from your id.

**Comment by vahidhedayati** [comment] 2015-05-28 19:52
Here is a really good example:

https://github.com/grails-samples/grails-petclinic/blob/master/grails-app/services/org/grails/samples/PetclinicService.groovy
```groovy
Visit createVisit(long petId, String description, Date date) {
		def visit = new Visit(pet: Pet.load(petId), description: description, date: date)
		visit.save()
		visit
	}

```

Where they load petId well they get the object and save it in the new call, usually though :
```
visit.save(flush:true)
```
If you are going to interact with that data immediately

**Comment by biosystem** [comment] 2015-05-28 19:58
I'm really new to Grails I 'm Delphi Developer

**Comment by biosystem** [comment] 2015-05-28 20:04
Example supplier saving correctly in table title fornecedor_id field
<label for="fornecedor">
            <g:message code="contasPagar.fornecedor.label" default="Fornecedor"/>
            <span class="required-indicator">*</span>
        </label>
        <g:select id="fornecedor" name="fornecedor.id" from="${bioweb.Fornecedor.list()}" optionKey="id" required=""
                  value="${contasPagarInstance?.fornecedor?.id}" class="many-to-one"/>

**Comment by biosystem** [comment] 2015-05-28 20:11
Example scaffold
<label for="centrocustos">
            <g:message code="contasPagar.centrocustos.label" default="Centrocustos"/>
            <span class="required-indicator">*</span>
        </label>
        <g:select id="centrocustos" name="centrocustos.id" from="${bioweb.CentroCusto.list()}" optionKey="id" required=""
                  value="${contasPagarInstance?.centrocustos?.id}" class="many-to-one"/>

Example ajaxdependency

        <label>CentroCustos:</label>
        <g:loadjui/>
        <g:autocomplete
                id="primarySearch"
                name="centrocustos.id"
                domain='bioweb.CentroCusto'
                searchField='descricao'
                collectField='id'
                value="${contasPagarInstance?.centrocustos?.descricao}"
                max="10"
                order="asc"
                required="true"
        />

**Comment by vahidhedayati** [comment] 2015-05-28 20:17
but the DB field is not the domain object..

fornecedor_id 
```
value="${contasPagarInstance?.fornecedor?.id}" 
```
its a dot not hyphen in the value field so it should be the same in your case.
```
contasPagarInstance?.fornecedor?.id  
```
contasPagarInstance is the actual object. so lets say I have a domain class.
```groovy
Class ContasPagar {
    String name
    static hasMany = [ Fornecedor:fornecedor]
    String somethingElse
}
```

```groovy
Class Fornecedor {
    String otherName
    static belongsTo = [ contas:ContasPagar]
    String whatever
}
```

Usually when you see something.id it means its grabbing the Id of the linked element

So if you had a controller action:
```groovy
def myControllerAction(Long id) {
  def contasPagarInstance=ContasPagar.get(id)
  if (contasPagarInstance) { 
    render view: 'something', model: [contasPagarInstance:contasPagarInstance]
  }
}
```
In your something.gsp you could do :
```gsp
<g:each in="contasPagarInstance" var="myVar">
${myVar.name} ${myVar.id} ${myVar.somethingElse}

<g:each in="fornecedor" var="myOtherVar">
${myOtherVar.otherName} ${myOtherVar.whatever} ${myOtherVar.id}
</g:each>
</g:each>
```

so what you are looking at is contasPagarInstance.fornecedor.id  which is that second loop i.e. myOtherVar.id rather than myVar.id..

I think if you are still stuck on saving your object you could try illustrating your actual problem on stackoverflow.

**Comment by vahidhedayati** [comment] 2015-05-28 20:19
and what is it doing to save.. can you provide what this autocomplete posts to, you should be able to use the above method and actually grab the centrocustos object bound to the id you are sending and save that way.

**Comment by vahidhedayati** [comment] 2015-06-21 13:01
To finalise problem and solution:

https://github.com/vahidhedayati/testads5/blob/master/grails-app/views/myContinent/example.gsp#L18-L31

```
<g:autoCompletePrimary id="primarySearch1"
name="NAMEOFcontinentName"
domain='ajaxdependancyselectexample.MyContinent'
searchField='continentName'
collectField='id'
hidden='hidden3'
value=''/>

<input type=hidden id="hidden3" name="continentId" value=""/>
```

A requirement to select value and save id best to use <g:autoCompletePrimary in grails2 and <ads:autoCompletePrimary  in grails 3

**Comment by biosystem** [comment] 2015-06-22 12:52
If it send me the Example for download via git I want to test the example and see how it was .

Thank you.

**Comment by vahidhedayati** [comment] 2015-06-23 20:17
You mean you want live working site, sure no problems you have the metal(server) and the internet :) otherwise just download the demo site and do run grails run-app on your local PC hehe.

I thought yours was working ? :)

The actual issue was bound to the code checked in to grails 3 branch so I added the above comments to finalise the issue, what was done as in the issues faced. With the comment being the final fix for this problem which was to use <g:selectPrimary and have a hidden field to store the autocomplete selection.

**Comment by vahidhedayati** [comment] 2015-07-31 18:02
Will close this issue - I think it is now resolved :)

**Closed by vahidhedayati** 2015-07-31 18:02 UTC
